### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by Sammidysam** [wl-acsl/toasty-penguin-party#1]
Do we want to change the name of this to something like Penguin Toast Collection?  I feel like this resembles pool less than we would think, so it seems strange to use that in our title.

**Comment by Sammidysam** [comment]
Thou shalt rename it to "Toasty Penguin Party".

**Comment by cg505** [comment]
On it.

**Comment by Sammidysam** [comment]
We still need to update the files according to the name change.
