### ISSUE TITLE
Field size

### ISSUE THREAD

**Issue by Ikemo** [wl-acsl/toasty-penguin-party#2]
How big are we making the grid/ where should we put the code for it/ are we still doing this project

**Comment by thesephist** [comment]
How about a nice, even 64 by 64

And I don't know. Having one performance per day is kind of tough, it turns out. I'm getting there. 
- Linus Lee

**Comment by Ikemo** [comment]
Should we do it in location?
Should it be an array?

**Comment by Ikemo** [comment]
I added in penguin. 64 by 64 took way too long to load on my computer so I made it 10 by 10. :)

**Comment by Sammidysam** [comment]
Sorry I didn't see this earlier!

> are we still doing this project

Since people did not request a meeting last Friday, our goal is to complete the game over the summer so that we can use it for the club rush next year.  No rush at all now.

**Comment by Ikemo** [comment]
Oh okay.
